# Ensure no markdown processing
markdown: kramdown

# Site settings
title: "Khim V. Cortez Portfolio"
description: "A student portfolio for EDM subject at City College of Angeles"

url: "https://your-username.github.io"  # Use your GitHub Pages URL

# Author info
author:
  name: "Khim Cortez"
  email: "kcortez24-0173@cca.edu.ph"
  url: "https://github.com/crtz"

# Build settings
markdown: kramdown

# Theme options (optional if you're using a theme)
theme: jekyll-theme-cayman  # Example: Change this if you want a theme
