# _config.yml for GitHub Pages (EDM Portfolio)

# Disable Jekyll processing (you are using only HTML/CSS)
# You still need to create a `.nojekyll` file in your repo root
exclude:
  - README.md
  - LICENSE
  - _config.yml

# If your site is published at https://crtzk.github.io/EDM/
baseurl: "/EDM"

# Optional metadata
title: "Khim V. Cortez Portfolio"
description: "Student portfolio for EDM subject at City College of Angeles"
