# Basic site information
title: "Khim V. Cortez's Portfolio"
description: "Information Systems Student"

# URL of your GitHub Pages site (replace with your actual URL)
url: "https://your-github-username.github.io"
baseurl: "/"

# Social Links (optional)
social:
  github: "https://github.com/crtzk"  # Replace with your GitHub link
