title: "Khim V. Cortez Portfolio"
description: "A portfolio showcasing the work and projects of Khim V. Cortez, a student in Bachelor of Science in Information Systems."
baseurl: "/"
url: "https://your-username.github.io"  # Replace with your GitHub username and repo URL (e.g., https://crtzk.github.io)

author:
  name: "Khim V. Cortez"
  email: "kcortez24-0173@cca.edu.ph"  # Replace with your email (optional)
  url: "https://github.com/crtzk"  # Replace with your GitHub profile URL

theme: "minimal"  # You can replace this with your preferred theme (this is optional)
