# Prevent Jekyll from processing files (good for plain HTML sites)
# and avoid unnecessary build issues
exclude:
  - README.md
  - LICENSE
  - _config.yml

# Set the base URL if you're hosting in a subdirectory (optional)
# baseurl: "/EDM"  # uncomment if your GitHub repo is named EDM

# Site info (optional metadata)
title: "Khim V. Cortez Portfolio"
description: "Student Portfolio for EDM Course at City College of Angeles"
