# _config.yml for GitHub Pages - EDM Portfolio by Khim V. Cortez

# Prevent Jekyll from interfering with plain HTML files
exclude:
  - README.md
  - LICENSE
  - _config.yml

# Set this if your repo is not a user/organization site
baseurl: "/EDM"  # This is needed for correct relative paths if you use subfolders

# Optional metadata (not used by your site, but good for documentation)
title: "Khim V. Cortez Portfolio"
description: "A student portfolio for EDM subject at City College of Angeles"

# Ensure no markdown processing
markdown: kramdown
